"""third migrations

Revision ID: 01dcde1f4847
Revises: a794005aedcb
Create Date: 2023-07-17 18:48:38.812994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01dcde1f4847'
down_revision = 'a794005aedcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
