"""third migrations

Revision ID: 13d225fba129
Revises: 2ab8c4408551
Create Date: 2023-07-17 18:52:38.598871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d225fba129'
down_revision = '2ab8c4408551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
