"""third migrations

Revision ID: 282af94fa871
Revises: 88559cdc95b9
Create Date: 2023-07-17 18:00:28.985370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282af94fa871'
down_revision = '88559cdc95b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
