"""third migrations

Revision ID: 2920c74a2706
Revises: b6925680f92e
Create Date: 2023-07-17 18:24:49.785986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2920c74a2706'
down_revision = 'b6925680f92e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
