"""third migrations

Revision ID: 2ab8c4408551
Revises: 38649c3d8781
Create Date: 2023-07-17 18:51:44.639891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab8c4408551'
down_revision = '38649c3d8781'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
