"""third migrations

Revision ID: 2f3c61bf1822
Revises: 95bc99467578
Create Date: 2023-07-17 18:59:17.041595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3c61bf1822'
down_revision = '95bc99467578'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
