"""third migrations

Revision ID: 31b25d6eb841
Revises: e185f00d2ea1
Create Date: 2023-07-17 18:43:57.692800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b25d6eb841'
down_revision = 'e185f00d2ea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
