"""third migrations

Revision ID: 3371614e2bf2
Revises: 31b25d6eb841
Create Date: 2023-07-17 18:46:33.594482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3371614e2bf2'
down_revision = '31b25d6eb841'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
