"""third migrations

Revision ID: 38649c3d8781
Revises: 4ac08d282187
Create Date: 2023-07-17 18:51:12.223716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38649c3d8781'
down_revision = '4ac08d282187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
