"""third migrations

Revision ID: 4ac08d282187
Revises: c15e92cdc05f
Create Date: 2023-07-17 18:50:11.433803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac08d282187'
down_revision = 'c15e92cdc05f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
