"""third migrations

Revision ID: 5d2ece6c00e7
Revises: 9f25472d6f9a
Create Date: 2023-07-17 18:55:21.246923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2ece6c00e7'
down_revision = '9f25472d6f9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
