"""third migrations

Revision ID: 88559cdc95b9
Revises: 068bcd27a9ca
Create Date: 2023-07-17 16:54:25.050696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88559cdc95b9'
down_revision = '068bcd27a9ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
