"""third migrations

Revision ID: 8abae29ca33e
Revises: 2920c74a2706
Create Date: 2023-07-17 18:35:43.332502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abae29ca33e'
down_revision = '2920c74a2706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
