"""third migrations

Revision ID: 90dcf87600d3
Revises: 9f4e6b433612
Create Date: 2023-07-17 18:56:38.731680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dcf87600d3'
down_revision = '9f4e6b433612'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
