"""third migrations

Revision ID: 95bc99467578
Revises: 90dcf87600d3
Create Date: 2023-07-17 18:58:40.375908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bc99467578'
down_revision = '90dcf87600d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
