"""third migrations

Revision ID: 9f25472d6f9a
Revises: b206f134b10d
Create Date: 2023-07-17 18:54:26.297331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f25472d6f9a'
down_revision = 'b206f134b10d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
