"""third migrations

Revision ID: 9f4e6b433612
Revises: 5d2ece6c00e7
Create Date: 2023-07-17 18:56:10.930070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4e6b433612'
down_revision = '5d2ece6c00e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
