"""third migrations

Revision ID: a794005aedcb
Revises: 3371614e2bf2
Create Date: 2023-07-17 18:46:56.554641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a794005aedcb'
down_revision = '3371614e2bf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
