"""third migrations

Revision ID: adf3d8dcaffb
Revises: c962defaa5ea
Create Date: 2023-07-17 18:42:42.594031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf3d8dcaffb'
down_revision = 'c962defaa5ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
