"""third migrations

Revision ID: c15e92cdc05f
Revises: 01dcde1f4847
Create Date: 2023-07-17 18:49:46.327660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15e92cdc05f'
down_revision = '01dcde1f4847'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
