"""third migrations

Revision ID: c962defaa5ea
Revises: 8abae29ca33e
Create Date: 2023-07-17 18:39:54.809128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c962defaa5ea'
down_revision = '8abae29ca33e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
